version: "3.9"  # Version de la spécification Docker Compose utilisée

services:
  app:  # Définition du service nommé "app"
    build: 
      context: .  # Le contexte de construction est le répertoire courant
      args:
        - DEV=true  # Argument de construction passé au Dockerfile
    ports:
      - "8000:8000"  # Mappe le port 8080 de l'hôte au port 8080 du conteneur
    volumes:
      - .:/app/app  # Monte le répertoire courant de l'hôte dans le conteneur sous /app/app
    command: >
      sh -c "python manage.py runserver 0.0.0:8000"  